remove sse mfpmath from x86 build
building on alpine llvm fails with error:
```
error: the 'sse' unit is not supported with this instruction set
```
due to `mfpmath` being implicitly set to `see`

set `mfpmath` to `387`

Signed-off-by: Pepper Gray <hello@peppergray.xyz>